# Generated by Django 3.1.4 on 2020-12-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('open', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Цена открытия')),
                ('high', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Максимальная цена')),
                ('low', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Минимальная цена')),
                ('close', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Цена закрытия')),
                ('currency1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_currency', to='stock.currency', verbose_name='Валюта 1')),
                ('currency2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_currency', to='stock.currency', verbose_name='Валюта 2')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency1', 'currency2'],
            },
        ),
    ]
