# Generated by Django 3.1.5 on 2021-03-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividend',
        ),
    ]
