# Generated by Django 3.1.5 on 2021-02-27 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='no-img.jpg', upload_to='assets/images')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='none@email.com', max_length=254)),
                ('birth_date', models.DateField(blank=True, default='1999-12-31')),
                ('bio', models.TextField(blank=True, default='')),
                ('open_portfolio', models.BooleanField(default=False)),
                ('analytics_currency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stock.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
