# Generated by Django 3.1.4 on 2020-12-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Брокер',
                'verbose_name_plural': 'Брокеры',
                'ordering': ['broker_title'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Торговая операция',
                'verbose_name_plural': 'Торговые операции',
                'ordering': ['tt_title'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('cost_without_nkd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость без НКД')),
                ('nkd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='НКД')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Общая стоимость')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Комиссия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.currency', verbose_name='Валюта')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='Идентификатор')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.transactiontype', verbose_name='Тип операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-date', '-time', 'total_cost'],
            },
        ),
        migrations.CreateModel(
            name='BrokerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='imported_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.broker', verbose_name='Брокер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
