# Generated by Django 3.1.4 on 2020-12-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Брокер',
                'verbose_name_plural': 'Брокеры',
                'ordering': ['broker_title'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_ticker', models.CharField(max_length=6, unique=True, verbose_name='Идентификатор')),
                ('currency_rus', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['currency_ticker'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_title', models.CharField(max_length=100, verbose_name='Индустрия')),
                ('industry_rus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Индустрия ru')),
            ],
            options={
                'verbose_name': 'Индустрия',
                'verbose_name_plural': 'Индустрии',
                'ordering': ['industry_title'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_title', models.CharField(max_length=50, unique=True, verbose_name='Сектор')),
                ('sector_rus', models.CharField(default='', max_length=50, verbose_name='Сектор ru')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сектора',
                'ordering': ['sector_title'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Индентификатор')),
                ('ticker_yf', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Индентификатор для Yahoo Finance')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='documents/logos', verbose_name='Логотип')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.currency', verbose_name='Валюта')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.industry', verbose_name='Индустрия')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.sector', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Торговая операция',
                'verbose_name_plural': 'Торговые операции',
                'ordering': ['tt_title'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('open', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Цена открытия')),
                ('high', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Максимальная цена')),
                ('low', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Минимальная цена')),
                ('close', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Цена закрытия')),
                ('volume', models.IntegerField(verbose_name='Объём торгов')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock', verbose_name='Индентификатор')),
            ],
            options={
                'verbose_name': 'Котировка',
                'verbose_name_plural': 'Котировки',
                'ordering': ['-date', 'ticker'],
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.sector'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('cost_without_nkd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость без НКД')),
                ('nkd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='НКД')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Общая стоимость')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Комиссия')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.currency', verbose_name='Валюта')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock', verbose_name='Идентификатор')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.transactiontype', verbose_name='Тип операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-date', '-time', 'total_cost'],
            },
        ),
        migrations.CreateModel(
            name='BrokerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='imported_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.broker', verbose_name='Брокер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
