# Generated by Django 3.1.4 on 2021-01-02 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_currencycourse'),
        ('portfolio', '0002_portfoliostaterow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliostaterow',
            options={'ordering': ['user', 'ticker'], 'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
        ),
        migrations.AddField(
            model_name='portfoliostaterow',
            name='average_sell_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Средняя цена продажи'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliostaterow',
            unique_together={('user', 'ticker', 'state')},
        ),
        migrations.RemoveField(
            model_name='portfoliostaterow',
            name='change',
        ),
        migrations.RemoveField(
            model_name='portfoliostaterow',
            name='date',
        ),
    ]
