# Generated by Django 3.1.4 on 2021-01-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210102_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-date', 'total_cost'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='cost_without_nkd',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='nkd',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='time',
        ),
    ]
